### ISSUE TITLE
dns_get_record(): DNS Query failed

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#241]
for values of ```foo.example.com``` which are valid hostnames, ixp4 just threw up:

```
Message: dns_get_record(): DNS Query failed
Line: 323
File: /blah/application/controllers/SwitchController.php

Trace:

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'dns_get_record(...', '/blah/...', 323, Array)
#1 /blah/application/controllers/SwitchController.php(323): dns_get_record('foo.example.com', 134217728)
#2 /blah/application/controllers/SwitchController.php(282): SwitchController->_resolve('foo.example.com', 134217728)
#3 /blah/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): SwitchController->addBySnmpAction()
```

**Comment by barryo** [comment]
Local DNS server issue -> closing.
