### ISSUE TITLE
v4 - MySQL >= 5.7.5 and ONLY_FULL_GROUP_BY breaks some queries

### ISSUE THREAD

**Issue by LindsayHill** [inex/IXP-Manager#263]
(nb this is a low priority issue, as it only affects v4 & recent MySQL builds)
I have been testing IXP-Manager v4 with Ubuntu 16.04. This includes MySQL 5.7.12.

MySQL >= 5.7.5 sets the [ONLY_FULL_GROUP_BY sql_mode](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html) by default. This breaks some IXP-Manager queries, e.g. if I go to the interfaces link, I get an error like this:
```Doctrine\DBAL\Exception\DriverException
File
/usr/local/ixp/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
115
Message
An exception occurred while executing 'SELECT v0_.id AS id_0, c1_.name AS name_1, c1_.id AS id_2, c1_.shortname AS shortname_3, COUNT(p2_.id) AS sclr_4, COUNT(p3_.id) AS sclr_5, l4_.name AS name_6, s5_.name AS name_7, s6_.type AS type_8, s6_.name AS name_9, SUM(p7_.speed) AS sclr_10, COUNT(p7_.id) AS sclr_11 FROM virtualinterface v0_ LEFT JOIN cust c1_ ON v0_.custid = c1_.id LEFT JOIN physicalinterface p7_ ON v0_.id = p7_.virtualinterfaceid LEFT JOIN switchport s6_ ON p7_.switchportid = s6_.id LEFT JOIN physicalinterface p2_ ON p7_.id = p2_.fanout_physical_interface_id LEFT JOIN physicalinterface p3_ ON p7_.fanout_physical_interface_id = p3_.id LEFT JOIN switch s5_ ON s6_.switchid = s5_.id LEFT JOIN cabinet c8_ ON s5_.cabinetid = c8_.id LEFT JOIN location l4_ ON c8_.locationid = l4_.id GROUP BY v0_.name, v0_.description, v0_.mtu, v0_.trunk, v0_.channelgroup, v0_.id, v0_.custid': SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ixp.l4_.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Code
0

Trace
#0 /usr/local/ixp/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /usr/local/ixp/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT v0_.id A...', Array)
#2 /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT v0_.id A...', Array, Array, NULL)
#3 /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#5 /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 2)
#6 /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(739): Doctrine\ORM\AbstractQuery->execute(NULL, 2)
#7 /usr/local/ixp/application/controllers/VirtualInterfaceController.php(131): Doctrine\ORM\AbstractQuery->getArrayResult()
#8 /usr/local/ixp/vendor/opensolutions/oss-framework/src/OSS/Controller/Action/Trait/Doctrine2Frontend.php(190): VirtualInterfaceController->listGetData()
#9 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): IXP_Controller_Frontend->listAction()
#10 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('listAction')
#11 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#13 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#14 /usr/local/ixp/app/Exceptions/Handler.php(59): Zend_Application->run()
#15 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(80): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#16 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(54): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#17 /usr/local/ixp/bootstrap/cache/compiled.php(3271): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /usr/local/ixp/bootstrap/cache/compiled.php(9914): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /usr/local/ixp/bootstrap/cache/compiled.php(9899): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /usr/local/ixp/bootstrap/cache/compiled.php(2363): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /usr/local/ixp/bootstrap/cache/compiled.php(2347): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#26 /usr/local/ixp/public/index.php(97): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#27 {main}
```

This is due to the ONLY_FULL_GROUP_BY change. I can change this mode, and the query works, e.g.:

```
mysql> SET sql_mode='';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> SELECT v0_.id AS id_0, c1_.name AS name_1, c1_.id AS id_2, c1_.shortname AS shortname_3, COUNT(p2_.id) AS sclr_4, COUNT(p3_.id) AS sclr_5, l4_.name AS name_6, s5_.name AS name_7, s6_.type AS type_8, s6_.name AS name_9, SUM(p7_.speed) AS sclr_10, COUNT(p7_.id) AS sclr_11 FROM virtualinterface v0_ LEFT JOIN cust c1_ ON v0_.custid = c1_.id LEFT JOIN physicalinterface p7_ ON v0_.id = p7_.virtualinterfaceid LEFT JOIN switchport s6_ ON p7_.switchportid = s6_.id LEFT JOIN physicalinterface p2_ ON p7_.id = p2_.fanout_physical_interface_id LEFT JOIN physicalinterface p3_ ON p7_.fanout_physical_interface_id = p3_.id LEFT JOIN switch s5_ ON s6_.switchid = s5_.id LEFT JOIN cabinet c8_ ON s5_.cabinetid = c8_.id LEFT JOIN location l4_ ON c8_.locationid = l4_.id GROUP BY v0_.name, v0_.description, v0_.mtu, v0_.trunk, v0_.channelgroup, v0_.id, v0_.custid;
+------+---------+------+-------------+--------+--------+------------+----------+--------+------------------+---------+---------+
| id_0 | name_1  | id_2 | shortname_3 | sclr_4 | sclr_5 | name_6     | name_7   | type_8 | name_9           | sclr_10 | sclr_11 |
+------+---------+------+-------------+--------+--------+------------+----------+--------+------------------+---------+---------+
|    1 | HEAnet  |    2 | heanet      |      0 |      0 | Location 1 | Switch 1 |      1 | GigabitEthernet3 |    2000 |       2 |
|    2 | HEAnet  |    2 | heanet      |      0 |      0 | Location 1 | Switch 2 |      1 | GigabitEthernet1 |    1000 |       1 |
|    3 | PCH DNS |    3 | pchdns      |      0 |      0 | Location 1 | Switch 1 |      1 | GigabitEthernet8 |     100 |       1 |
|    4 | AS112   |    4 | as112       |      0 |      0 | Location 1 | Switch 1 |      1 | GigabitEthernet6 |      10 |       1 |
|    5 | AS112   |    4 | as112       |      0 |      0 | Location 1 | Switch 2 |      1 | GigabitEthernet6 |      10 |       1 |
|    6 | Imagine |    5 | imagine     |      0 |      0 | Location 1 | Switch 1 |      1 | GigabitEthernet9 |    1000 |       1 |
|    7 | Imagine |    5 | imagine     |      0 |      0 | Location 1 | Switch 2 |      1 | GigabitEthernet8 |   10000 |       1 |
+------+---------+------+-------------+--------+--------+------------+----------+--------+------------------+---------+---------+
7 rows in set (0.01 sec)

mysql>
```

I haven't yet worked through exactly what changes need to be made to the query, but as a short-term workaround, I have set this in `my.cnf`:

```
[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

I'm not sure what the 'right' long-term solution is. Change the query somehow? Or configure the application to use the older sql_mode?

**Comment by barryo** [comment]
> I'm not sure what the 'right' long-term solution is. Change the query somehow?

Yip, definitely fix the query 😄 

Thanks for opening this issue. I tend to use MariaDB so was oblivious to this change in MySQL.

**Comment by LindsayHill** [comment]
Awesome - thanks for the quick turnaround. I'm setting up a test rig on Ubuntu 16.04, and I fully expect a few issues along these lines. But if figure someone has to encounter the problems, because plenty of people will start targeting 16.04 this year. I might aim to get the Vagrant build working with 16.04. Looks like a few small changes so far, but nothing too crazy

**Comment by barryo** [comment]
Hey @LindsayHill - just note the following commit re Vagrant:

https://github.com/inex/IXP-Manager/commit/d132c050884bef2ff3f8d10773a568f14b193e83

It's on a feature branch off v4 where most of my attention is right now. My plan would be to complete that, merge it into v4 branch and do an official release of v4 as v4.2.

**Comment by LindsayHill** [comment]
Oh, nice. I'll keep an eye on that branch
