### ISSUE TITLE
Cannot delete interfaces from Customer page

### ISSUE THREAD

**Issue by digitalandrei** [inex/IXP-Manager#397]
##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu 16.04

##### VERSION
```
define( 'APPLICATION_VERSION', '4.7.3' );
define( 'APPLICATION_VERDATE', '2018021900' );
```

##### ENVIRONMENT 
```
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

##### CONFIGURATION
```
APP_DEBUG=false
APP_TIMEZONE="Europe/Bucharest"
APP_LOG="single"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=true
IXP_AS112_UI_ACTIVE=true
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
GRAPHER_CACHE_ENABLED=true
CACHE_DRIVER=memcached
SESSION_DRIVER=file
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
GRAPHER_ACCESS_IXP=0
GRAPHER_ACCESS_INFRASTRUCTURE=1
GRAPHER_ACCESS_SWITCH=1
GRAPHER_ACCESS_TRUNK=1
```

##### SUMMARY
We cannot delete Physical Interfaces allocated to customers.

##### STEPS TO REPRODUCE
1. Go to customers
2. Select a customer and go to Ports
3. Edit any of the connections
4. Try to delete an interface using the trash bin button on the right
5. Click on Delete button when the popup appears

##### EXPECTED RESULTS
Interface is deleted.

##### ACTUAL RESULTS
Nothing happens after step 5.

##### IMPORTANCE
Very high

##### LOGS
When accessing the edit page the below message appears (/interfaces/virtual/edit/xxx). Nothing else appears when hitting the Delete button of step 5.

```
************************************************************************
****************************** EXCEPTIONS *******************************
************************************************************************

--------------------------- EXCEPTION --------------------------

Message: Invalid controller specified (js)
Line: 248
File: /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php

Trace:

#0 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#3 /srv/ixpmanager/app/Exceptions/Handler.php(62): Zend_Application->run()
#4 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 /srv/ixpmanager/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#24 /srv/ixpmanager/public/index.php(85): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#25 {main}
```

**Comment by yannrobin** [comment]
Hello,

This bug happen when you try to delete a Physical Interface or a VLAN Interface ?

**Comment by digitalandrei** [comment]
Hi Yann,

It happens for both Phys and VLAN Interface. It appeared recently as I can remember being able to delete interfaces some days ago. We updated twice since then using stardard upgrade procedure.

Let me know if I can provide any other information that can help.

Thank you

**Comment by yannrobin** [comment]
Hello,

It work for me in our dev environment.

Yes its look similar, I will let you know if we find anything.

Thanks

**Comment by steiostb** [comment]
> Hi Yann,
> 
> It happens for both Phys and VLAN Interface. It appeared recently as I can remember being able to delete interfaces some days ago. We updated twice since then using stardard upgrade procedure.
> 
> Let me know if I can provide any other information that can help.
> 
> PS: it looks similar to this bug report #398
> 
> Message: Invalid controller specified (favicon.ico)
> Line: 248
> File: /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
> 


I am able to delete a Physical Interface. I have updated my bug report #398 to include the correct output from storage/logs/laravel.log:
--------------------------- EXCEPTION --------------------------

Message: Undefined index: csrf-token
Line: 73
File: /usr/local/ixp/library/OSS/Controller/Action/Trait/CSRF.php

**Comment by digitalandrei** [comment]
This report can be closed. A recent git pull didn't work because of a conflict and I didn't observe it in time.

Thank you
