### ISSUE TITLE
bgp-summary.foil.php fails because $p->description is missing

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#494]
##### ISSUE TYPE

Bug Report

##### OS

Description:    Ubuntu 16.04.5 LTS

##### VERSION

```
define( 'APPLICATION_VERSION', '4.8.0' );
define( 'APPLICATION_VERDATE', '201807030000' );
```

##### ENVIRONMENT 

```
PHP 7.0.31-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:00:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.31-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

##### CONFIGURATION

```
APP_DEBUG=false
APP_URL="https://manager.minap.it"
APP_TIMEZONE="Europe/Rome"
APP_LOG="daily"
APP_LOG_LEVEL=debug
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=false
IXP_FE_FRONTEND_DISABLED_LOGO=false
GRAPHER_BACKENDS="mrtg"
GRAPHER_CACHE_ENABLED=true
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/var/lib/mrtg/"
GRAPHER_BACKEND_MRTG_LOGDIR="/var/lib/mrtg/"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
VIEW_SKIN="minap"
VIEW_SMARTY_SKIN="minap"
CACHE_DRIVER=memcached
SESSION_LIFETIME=10080
SESSION_DRIVER=memcached
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
FORMER_LIVE_VALIDATION=false
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=true
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
IXP_FE_LAYER2_ADDRESSES_CUST_CAN_EDIT=true
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MIN_ADDRESSES=1
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MAX_ADDRESSES=2
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_CUSTOMER_CHANGE=true
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_SUPERUSER_CHANGE=true
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_CHANGE_DEST="noc@minap.it"
IXP_FE_FRONTEND_DISABLED_RS_PREFIXES=true
```

##### SUMMARY

https://manager.minap.it/lg/rs1-ipv4 crashes because ```$p->description``` in ```resources/views/services/lg/bgp-summary.foil.php``` is not defined for one of the customers (even if I can see the description in the customer page as expected).

It used to work until a few months ago, but I could not find out what has changed.

Log:

```
[2018-12-14 01:14:00] production.ERROR: Undefined property: stdClass::$description {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$description at /srv/ixpmanager/resources/views/services/lg/bgp-summary.foil.php:35)
[stacktrace]
#0 /srv/ixpmanager/resources/views/services/lg/bgp-summary.foil.php(35): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', '/srv/ixpmanager...', 35, Array)
#1 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(287): require('/srv/ixpmanager...')
#2 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(231): Foil\\Template\\Template->collect('/srv/ixpmanager...')
#3 /srv/ixpmanager/vendor/foil/foil/src/Engine.php(307): Foil\\Template\\Template->render(Array)
...
```

I worked around this by modifying the template:

```
-            <?= isset( $p->description_short ) ? $p->description_short : $p->description ?>
+            <?= isset( $p->description_short ) ? $p->description_short : isset($p->description) ? $p->description : "???" ?>

-                data-protocol="<?= $name ?>" title="<?= $p->description ?>">Details</a>
+                data-protocol="<?= $name ?>" title="<?= isset($p->description) ? $p->description : "???" ?>">Details</a>
```

**Comment by barryo** [comment]
This is then an issue with the Bird's Eye parser - if you want to open an issue on https://github.com/inex/birdseye then we'll have a look during the next development cycle for that.
