### ISSUE TITLE
Superuser accounts aren't working anymore after upgrading

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#665]
Hi,

after upgrading to 5.6.0 we can not login using the superuser account (Permission level 3 in DB) --> Login works but the page is blank. Only the header showes up. The login for normal members is still working. 

The admin login was working the last time on Version 5.3. It stopped working after upgrading to Version 5.4. This manager installation was installed using version 3 or 4, so there were many changes since the first installation.
If I change the user permission in the DB --> CustAdmin, I can login again

In the laravel.log I can see the following:
````
[stacktrace]
[2020-08-05 13:52:31] production.ERROR: customers is not defined. {"userId":1,"exception":"[object] (RuntimeException(code: 0): customers is not defined. at /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php:343)
[stacktrace]
#0 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(365): Foil\\Extensions\\Helpers->getIn()
#1 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(240): Foil\\Extensions\\Helpers->get()
#2 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(121): Foil\\Extensions\\Helpers->raw()
#3 [internal function]: Foil\\Extensions\\Helpers->variable()
#4 /srv/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(168): call_user_func_array()
#5 /srv/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(195): Foil\\Kernel\\Command->execute()
#6 [internal function]: Foil\\Kernel\\Command->doRun()
#7 /srv/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(181): call_user_func_array()
#8 [internal function]: Foil\\Kernel\\Command->doRunIsolated()
#9 /srv/ixpmanager/vendor/foil/foil/src/Kernel/Command.php(104): call_user_func_array()
#10 [internal function]: Foil\\Kernel\\Command->run()
#11 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(164): call_user_func_array()
#12 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(113): Foil\\Template\\Template->run()
#13 /srv/ixpmanager/resources/skins/kleyrex/layouts/menus/superuser.foil.php(124): Foil\\Template\\Template->__get()
#14 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(287): require('/srv/ixpmanager...')
#15 /srv/ixpmanager/vendor/foil/foil/src/Template/Template.php(231): Foil\\Template\\Template->collect()
#16 /srv/ixpmanager/vendor/foil/foil/src/Engine.php(307): Foil\\Template\\Template->render()
[...]
````

I can't use the mailinglist at the moment, do you have any clue where the problem could be? :-/
Thanks!

//
Ubuntu 20.04 LTS
Apache2 + PHP 7.4.8

**Comment by netfreak98** [comment]
Fixed, some old skinning files caused this issue :) --> closed

**Comment by barryo** [comment]
Self-closing issues -> the best kind 🍻
