### ISSUE TITLE
logger: "Driver [null] is not supported."

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#903]
##### ISSUE TYPE

Bug Report

##### OS

Ubuntu 24.04 LTS

##### VERSION

```
define( 'APPLICATION_VERSION', '6.4.1' );
define( 'APPLICATION_VERDATE', '2024060900' );
```

##### ENVIRONMENT 

```
PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies

ii  php-common                                       2:93ubuntu2                                   all          Common files for PHP packages
ii  php-pear                                         1:1.10.13+submodules+notgz+2022032202-2build1 all          PEAR Base System
ii  php8.3                                           8.3.6-0ubuntu0.24.04.1                        all          server-side, HTML-embedded scripting language (metapackage)
ii  php8.3-bcmath                                    8.3.6-0ubuntu0.24.04.1                        amd64        Bcmath module for PHP
ii  php8.3-cli                                       8.3.6-0ubuntu0.24.04.1                        amd64        command-line interpreter for the PHP scripting language
ii  php8.3-common                                    8.3.6-0ubuntu0.24.04.1                        amd64        documentation, examples and common module for PHP
ii  php8.3-curl                                      8.3.6-0ubuntu0.24.04.1                        amd64        CURL module for PHP
ii  php8.3-fpm                                       8.3.6-0ubuntu0.24.04.1                        amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php8.3-gd                                        8.3.6-0ubuntu0.24.04.1                        amd64        GD module for PHP
ii  php8.3-igbinary                                  3.2.13-1ubuntu3                               amd64        igbinary PHP serializer
ii  php8.3-intl                                      8.3.6-0ubuntu0.24.04.1                        amd64        Internationalisation module for PHP
ii  php8.3-mbstring                                  8.3.6-0ubuntu0.24.04.1                        amd64        MBSTRING module for PHP
ii  php8.3-memcache                                  8.0+4.0.5.2+3.0.9~20170802.e702b5f9+-8ubuntu1 amd64        memcache extension module for PHP
ii  php8.3-memcached                                 3.2.0+2.2.0-4ubuntu3                          amd64        memcached extension module for PHP, uses libmemcached
ii  php8.3-msgpack                                   1:2.2.0~rc2-3ubuntu1                          amd64        PHP extension for interfacing with MessagePack
ii  php8.3-mysql                                     8.3.6-0ubuntu0.24.04.1                        amd64        MySQL module for PHP
ii  php8.3-opcache                                   8.3.6-0ubuntu0.24.04.1                        amd64        Zend OpCache module for PHP
ii  php8.3-readline                                  8.3.6-0ubuntu0.24.04.1                        amd64        readline module for PHP
ii  php8.3-rrd                                       2.0.3+1.1.3-7ubuntu3                          amd64        PHP bindings to rrd tool system
ii  php8.3-snmp                                      8.3.6-0ubuntu0.24.04.1                        amd64        SNMP module for PHP
ii  php8.3-xml                                       8.3.6-0ubuntu0.24.04.1                        amd64        DOM, SimpleXML, XML, and XSL module for PHP
ii  php8.3-yaml                                      2.2.2+2.1.0+2.0.4+1.3.2-6ubuntu1              amd64        YAML-1.1 parser and emitter for PHP
ii  php8.3-zip                                       8.3.6-0ubuntu0.24.04.1                        amd64        Zip module for PHP
```

##### CONFIGURATION

```
APP_DEBUG=false
APP_URL="https://manager.minap.it"
APP_TIMEZONE="Europe/Rome"
APP_LOG="daily"
APP_LOG_LEVEL=debug
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=false
IXP_FE_FRONTEND_DISABLED_LOGO=false
IXP_FE_FRONTEND_DISABLED_PEERING_MATRIX=true
GRAPHER_BACKENDS="mrtg"
GRAPHER_CACHE_ENABLED=true
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/var/lib/mrtg/"
GRAPHER_BACKEND_MRTG_LOGDIR="/var/lib/mrtg/"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
VIEW_SKIN="minap"
VIEW_SMARTY_SKIN="minap"
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq3
AUTH_PEERINGDB_ENABLED=true
PEERINGDB_OAUTH_CLIENT_ID="..."
PEERINGDB_OAUTH_CLIENT_SECRET="..."
PEERINGDB_OAUTH_REDIRECT="https://manager.minap.it/auth/login/peeringdb/callback"
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=true
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
IXP_FE_FRONTEND_DISABLED_FILTERED_PREFIXES=true
IXP_FE_LAYER2_ADDRESSES_CUST_CAN_EDIT=true
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MIN_ADDRESSES=1
IXP_FE_LAYER2_ADDRESSES_CUST_PARAMS_MAX_ADDRESSES=2
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_CUSTOMER_CHANGE=true
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_SUPERUSER_CHANGE=false
IXP_FE_LAYER2_ADDRESSES_EMAIL_ON_CHANGE_DEST="noc@minap.it"
GRAPHER_ACCESS_IXP=0
GRAPHER_ACCESS_SWITCH=0
GRAPHER_ACCESS_CUSTOMER=1
GRAPHER_ACCESS_TRUNK=0
TELESCOPE_ENABLED=false
```

##### SUMMARY

The log is flooded by messages like these.

##### RELEVANT LOGS

```
[2024-08-22 16:50:01] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [null] is not supported. at /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:223)
[stacktrace]
#0 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(135): Illuminate\\Log\\LogManager->resolve()
#1 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(122): Illuminate\\Log\\LogManager->get()
#2 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(111): Illuminate\\Log\\LogManager->driver()
#3 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(117): Illuminate\\Log\\LogManager->channel()
#4 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError()
#5 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#6 /srv/ixpmanager/vendor/foil/foil/src/Template/Stack.php(24): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#7 /srv/ixpmanager/vendor/composer/ClassLoader.php(576): include('...')
#8 /srv/ixpmanager/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#9 /srv/ixpmanager/vendor/foil/foil/src/Providers/Core.php(91): Composer\\Autoload\\ClassLoader->loadClass()
#10 /srv/ixpmanager/vendor/pimple/pimple/src/Pimple/Container.php(122): Foil\\Providers\\Core->Foil\\Providers\\{closure}()
#11 /srv/ixpmanager/vendor/foil/foil/src/Providers/Core.php(101): Pimple\\Container->offsetGet()
#12 /srv/ixpmanager/vendor/pimple/pimple/src/Pimple/Container.php(122): Foil\\Providers\\Core->Foil\\Providers\\{closure}()
#13 /srv/ixpmanager/vendor/foil/foil/src/Providers/Blocks.php(76): Pimple\\Container->offsetGet()
#14 /srv/ixpmanager/vendor/foil/foil/src/Foil.php(108): Foil\\Providers\\Blocks->boot()
#15 /srv/ixpmanager/vendor/foil/foil/src/Foil.php(73): Foil\\Foil::setup()
#16 /srv/ixpmanager/vendor/foil/foil/inc/functions.php(43): Foil\\Foil::boot()
#17 /srv/ixpmanager/app/Providers/FoilServiceProvider.php(58): Foil\\engine()
#18 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): IXP\\Providers\\FoilServiceProvider->IXP\\Providers\\{closure}()
#19 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#20 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#21 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#22 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#23 /srv/ixpmanager/app/Providers/FoilServiceProvider.php(72): Illuminate\\Foundation\\Application->make()
#24 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1279): IXP\\Providers\\FoilServiceProvider->IXP\\Providers\\{closure}()
#25 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Illuminate\\Container\\Container->fireCallbackArray()
#26 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): Illuminate\\Container\\Container->fireResolvingCallbacks()
#27 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#28 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#29 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#30 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\\Foundation\\Application->make()
#31 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(1029): app()
#32 /srv/ixpmanager/app/Providers/AppServiceProvider.php(56): view()
#33 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): IXP\\Providers\\AppServiceProvider->boot()
#34 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#36 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#38 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(929): Illuminate\\Container\\Container->call()
#39 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Illuminate\\Foundation\\Application->bootProvider()
#40 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#41 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): array_walk()
#42 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#43 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#44 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
#45 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#46 /srv/ixpmanager/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#47 {main}
"} 
```

**Comment by rfc1036** [comment]
I am still seeing this error after switching to PHP 8.0.

**Comment by rfc1036** [comment]
It does. The file is unmodified, HEAD is 81f57c289632617d184eaf70b761b19438e91d65 (release-v6).

Logs are still being written, this is where the errors I reported come from:

```
-rw-r--r-- 1 www-data www-data  628456 Aug 27 12:55 laravel-2024-08-27.log
-rw-rw-r-- 1 www-data www-data 9362818 Aug 27 12:56 laravel.log
```

**Comment by listerr** [comment]
I get similar error after upgrading to 6.4.2 today:

```
[2025-02-19 19:46:05] laravel.WARNING: Return type of Foil\Template\Stack::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/ixpmanager/vendor/foil/foil/src/Template/Stack.php on line 86

[2025-02-19 12:43:41] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [null] is not supported. at /srv/ixpmanager/vendor/laravel/framework/s
rc/Illuminate/Log/LogManager.php:223)
[stacktrace]
#0 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(135): Illuminate\\Log\\LogManager->resolve()
#1 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(122): Illuminate\\Log\\LogManager->get()
#2 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(111): Illuminate\\Log\\LogManager->driver()
#3 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(117): Illuminate\\Log\\LogManager->channel()
#4 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError()
#5 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#6 /srv/ixpmanager/vendor/foil/foil/src/Template/Stack.php(24): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#7 /srv/ixpmanager/vendor/composer/ClassLoader.php(576): include('...')
#8 /srv/ixpmanager/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#9 /srv/ixpmanager/vendor/foil/foil/src/Providers/Core.php(91): Composer\\Autoload\\ClassLoader->loadClass()
#10 /srv/ixpmanager/vendor/pimple/pimple/src/Pimple/Container.php(122): Foil\\Providers\\Core->Foil\\Providers\\{closure}()
#11 /srv/ixpmanager/vendor/foil/foil/src/Providers/Core.php(101): Pimple\\Container->offsetGet()
#12 /srv/ixpmanager/vendor/pimple/pimple/src/Pimple/Container.php(122): Foil\\Providers\\Core->Foil\\Providers\\{closure}()
#13 /srv/ixpmanager/vendor/foil/foil/src/Providers/Blocks.php(76): Pimple\\Container->offsetGet()
#14 /srv/ixpmanager/vendor/foil/foil/src/Foil.php(108): Foil\\Providers\\Blocks->boot()
#15 /srv/ixpmanager/vendor/foil/foil/src/Foil.php(73): Foil\\Foil::setup()
#16 /srv/ixpmanager/vendor/foil/foil/inc/functions.php(43): Foil\\Foil::boot()
#17 /srv/ixpmanager/app/Providers/FoilServiceProvider.php(58): Foil\\engine()
#18 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): IXP\\Providers\\FoilServiceProvider->IXP\\Providers\\{closure}()
#19 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#20 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(858): Illuminate\\Container\\Container->resolve()
#21 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#22 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Container\\Container->make()
#23 /srv/ixpmanager/app/Providers/FoilServiceProvider.php(72): Illuminate\\Foundation\\Application->make()
#24 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1279): IXP\\Providers\\FoilServiceProvider->IXP\\Providers\\{closure}()
#25 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Illuminate\\Container\\Container->fireCallbackArray()
#26 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): Illuminate\\Container\\Container->fireResolvingCallbacks()
#27 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(858): Illuminate\\Container\\Container->resolve()
#28 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#29 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Container\\Container->make()
#30 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\\Foundation\\Application->make()
#31 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(1029): app()
#32 /srv/ixpmanager/app/Providers/AppServiceProvider.php(56): view()
#33 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): IXP\\Providers\\AppServiceProvider->boot()
#34 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#36 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#38 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(931): Illuminate\\Container\\Container->call()
#39 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(912): Illuminate\\Foundation\\Application->bootProvider()
#40 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#41 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(911): array_walk()
#42 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#43 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#44 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Foundation\\Application->bootstrapWith()
#45 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#46 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#47 /srv/ixpmanager/public/index.php(88): Illuminate\\Foundation\\Http\\Kernel->handle()
#48 {main}

```

php version:

```
root@portal:~# php --version
PHP 8.3.16 (cli) (built: Jan 19 2025 13:45:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.16, Copyright (c), by Zend Technologies
```

Upgraded php from 8.0.

We don't appear to have changed the default logging config.

I've tried variations in .env but it doesn't seem to make any difference, e.g.:

```
# Laravel log format (storage/log). See config/log.php and
# https://laravel.com/docs/5.4/errors
#APP_LOG="single"
#APP_LOG=daily
LOG_CHANNEL=single

# info by default, one of: debug, info, notice, warning, error, critical, alert, emergency.
APP_LOG_LEVEL=debug
```

**Comment by rfc1036** [comment]
To make a long story short, PHP 8.3 is not supported and you need to either downgrade it to 8.0 using Ondrej's PPA or else gamble on upgrading IXP Manager to the still unreleased v7.

```
root@manager:~# cat /etc/apt/preferences.d/pin-php
# do not install by default
Package: *
Pin: release o=LP-PPA-ondrej-php
Pin-Priority: 100

Package: php-common
Pin: release o=LP-PPA-ondrej-php
Pin-Priority: 990
root@manager:~# cat /etc/apt/sources.list.d/ondrej.list
deb http://ppa.launchpad.net/ondrej/php/ubuntu noble main
root@manager:~#
```

**Comment by listerr** [comment]
Hmmmm. Should probably update the docs then, :) 

e.g.:

- https://docs.ixpmanager.org/latest/install/manually/
- https://www.ixpmanager.org/download/install

I would read "**PHP >= 8.0**" to mean "works with 8.3" which seems to be what it upgrades to.

There was some composer dependency which didn't seem to want to install with php8.0, hence I bumped the version.

I'll downgrade it to php8.1...

**Comment by listerr** [comment]
Downgraded to php8.1 but it seems to have started up with these errors again.. hmmmm...
